import { useEffect, useState } from "react";
import axios from "axios";
import { v4 as uuidv4 } from "uuid";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

// Import React Icons
import { FaClipboard, FaShareAlt, FaClipboardCheck } from "react-icons/fa";

function Refers() {
  const [referralLink, setReferralLink] = useState("");
  const [referralCode, setReferralCode] = useState("");

  useEffect(() => {
    const referralCode = uuidv4();
    const link = `http://localhost:5000/referral/${referralCode}`;
    setReferralLink(link);
    setReferralCode(referralCode);

    // Send the referral link to the backend
    
  }, []);


  const reffer_link_handaler = () => {

    axios
      .post("http://localhost:5000/referral", { referralCode: referralCode })
      .then((response) => console.log("Referral sent:", response.data))
      .catch((error) => console.error("Error sending referral:", error));

  }

  return (
    <div className="mt-10 ml-5 lg:ml-16">
      <div>
        <ToastContainer
          position="top-right"
          autoClose={3000}
          hideProgressBar={true}
          style={{ zIndex: 999999999 }}
        />
        <h1 className="text-2xl font-bold">Referral Program</h1>
        <p className="mt-2 text-white pt-2">
          Share your referral link with friends and earn rewards!
        </p>
        {referralLink && (
          <div className="mt-4 p-3 bg-[#cca354] border border-gray-300 border-solid rounded-lg mr-6">
            <p className="font-medium">Your Referral Link:</p>
            <div className="refferrel_Link_box w-full flex items-center justify-center  mt-4 mb-4 mt-1 border-2 border-[#a56b00] rounded">
              <input
                type="text"
                value={referralLink}
                readOnly
                className="w-full p-2 mt-1 border-2 border-amber-800 rounded"
              />
            </div>
            <button
              className="mt-2 px-4 py-2 bg-orange-500 text-white rounded hover:bg-orange-600 flex items-center"
              onClick={() => {
                navigator.clipboard.writeText(referralLink);
                toast.success("Copied Successfully!", {
                  position: "top-right",
                });


                reffer_link_handaler();
              }}
            >
              <FaClipboard className="mr-2" />
              Copy Link
            </button>
          </div>
        )}
      </div>

      <div className="reffereal-rules-box text-white">
        <div className="max-w-3xl lg:max-w-[90%] mx-auto mt-10 px-5 py-8 bg-[#cca354] rounded-lg shadow-lg">
          <h2 className="text-3xl font-semibold text-center text-white">
            Referral Program Rules
          </h2>
          <p className="text-center text-black mt-3">
            Refer your friends and earn rewards! Here's how our referral program
            works.
          </p>

          <div className="mt-8">
            <h3 className="text-2xl font-semibold text-black">
              1. How It Works
            </h3>
            <p className="mt-2 text-black">
              When you share your unique referral link and someone clicks on it,
              you'll earn 2.5% of the profit from their purchase. It’s that
              simple! The more referrals, the more you earn.
            </p>
          </div>

          <div className="mt-8">
            <h3 className="text-2xl font-semibold text-gray-800">
              2. Eligibility
            </h3>
            <p className="mt-2 text-black">
              - The referral program is open to all registered users of our
              platform. <br />- Referrals apply only to new users who click your
              unique referral link and complete a purchase or action.
            </p>
          </div>

          <div className="mt-8">
            <h3 className="text-2xl font-semibold text-gray-800">
              3. Referral Reward
            </h3>
            <p className="mt-2 text-black">
              You will receive 2.5% of the profit generated by each successful
              transaction made by a referred user. Rewards are credited to your
              account within 24–48 hours after the transaction is completed.
            </p>
          </div>

          <div className="mt-8">
            <h3 className="text-2xl font-semibold text-gray-800">
              4. How to Share Your Link
            </h3>
            <p className="mt-2 text-black">
              Share your unique referral link via social media, email, or other
              platforms. You’ll earn a reward when someone clicks your link and
              makes a purchase. Remember, the link is valid for 30 days from the
              first click.
            </p>
          </div>

          <div className="mt-8">
            <h3 className="text-2xl font-semibold text-gray-800">
              5. Referral Limitations
            </h3>
            <p className="mt-2 text-black">
              - The program is limited to **N** successful referrals per user.{" "}
              <br />- The referral reward cannot be combined with other
              promotions or discounts unless stated otherwise.
            </p>
          </div>

          <div className="mt-8">
            <h3 className="text-2xl font-semibold text-gray-800">
              6. Referral Link Usage
            </h3>
            <p className="mt-2 text-black">
              Your referral link can be shared freely, but spamming or using
              unethical practices (such as posting the link in restricted or
              inappropriate places) will result in disqualification from the
              program.
            </p>
          </div>

          <div className="mt-8">
            <h3 className="text-2xl font-semibold text-gray-800">
              7. Changes to the Program
            </h3>
            <p className="mt-2 text-black">
              We reserve the right to modify or terminate the referral program
              at any time. All changes will be communicated in advance through
              email or the website.
            </p>
          </div>

          <div className="mt-8">
            <h3 className="text-2xl font-semibold text-gray-800">
              8. Compliance
            </h3>
            <p className="mt-2 text-black">
              All participants must adhere to our general terms and conditions.
              Violations or fraudulent activity may result in disqualification
              from the program and forfeiture of any rewards earned.
            </p>
          </div>

          <div className="mt-8 text-center">
            <p className="text-lg font-medium text-black">
              Start sharing your referral link now and earn rewards!
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}

export default Refers;
